# Generated by Django 2.2.12 on 2020-05-12 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator_id', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
