# Generated by Django 2.2.10 on 2020-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirprojects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirproject',
            name='creator',
        ),
        migrations.AddField(
            model_name='dirproject',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
    ]
