# Generated by Django 2.2.10 on 2020-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirprojects', '0002_auto_20200317_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirproject',
            old_name='discription',
            new_name='description',
        ),
    ]
