version: '3'
    
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ocr_db
      MONGO_INITDB_USERNAME: test
      MONGO_INITDB_PASSWORD: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init-js:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Ocr
    ports:
      - 8000:8000
    links:
      - mongo
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/Ocr
    links:
      - mongo
    depends_on:
      - make_migrations
      
  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/Ocr
    links:
      - mongo
    depends_on:
      - mongo