# Generated by Django 2.2.12 on 2020-05-12 16:45

from django.db import migrations, models
import django.db.models.deletion
import functions.modelsFiledValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocrfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('get_text', models.CharField(max_length=200)),
                ('startX', models.FloatField(default=0)),
                ('endX', models.FloatField(default=0)),
                ('startY', models.FloatField(default=0)),
                ('endY', models.FloatField(default=0)),
                ('correction_rate', functions.modelsFiledValidator.PercentageField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback_text', models.CharField(blank=True, max_length=200)),
                ('is_exist', models.BooleanField(default=False)),
                ('ocrfiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='ocrfiles.Ocrfiles')),
            ],
        ),
    ]
