# Generated by Django 2.2.10 on 2020-04-07 06:45

from django.db import migrations
import functions.modelsFiledValidator


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='endX',
            field=functions.modelsFiledValidator.PercentageField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='endY',
            field=functions.modelsFiledValidator.PercentageField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='startX',
            field=functions.modelsFiledValidator.PercentageField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='startY',
            field=functions.modelsFiledValidator.PercentageField(default=0),
        ),
    ]
