# Generated by Django 2.2.10 on 2020-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_auto_20200407_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='endX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='endY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='startX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='validation',
            name='startY',
            field=models.FloatField(default=0),
        ),
    ]
