# Generated by Django 2.2.10 on 2020-04-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_auto_20200407_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='is_whole',
            field=models.BooleanField(default=False),
        ),
    ]
