# Generated by Django 2.2.10 on 2020-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_validation_is_whole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='is_whole',
        ),
    ]
