# Generated by Django 2.2.10 on 2020-03-16 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dirprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocrfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('file_extension', models.CharField(max_length=250)),
                ('upload_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('file_size', models.FloatField()),
                ('scanned_file', models.FileField(null=True, upload_to='Ocr_files/Ocr_Scanned_files/%Y/%m/')),
                ('dir_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_files', to='dirprojects.DirProject')),
            ],
        ),
        migrations.CreateModel(
            name='OcrConvertedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=250)),
                ('page_number', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='Ocr_files/Ocr_Converted_files/%Y/%m/')),
                ('ocrfiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_image', to='ocrfiles.Ocrfiles')),
            ],
        ),
    ]
