# Generated by Django 2.2.10 on 2020-03-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrfiles',
            name='dir_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocrfiles', to='dirprojects.DirProject'),
        ),
    ]
