# Generated by Django 2.2.12 on 2020-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrconvertedimage',
            name='image_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ocrconvertedimage',
            name='textRegion_image_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ocrfiles',
            name='scanned_file_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
