# Generated by Django 2.2.10 on 2020-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrfiles', '0002_auto_20200323_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrfiles',
            name='textRegion_file',
            field=models.FileField(null=True, upload_to='Ocr_files/Ocr_TextRegion_files/%Y/%m/'),
        ),
    ]
