# Generated by Django 2.2.10 on 2020-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrfiles', '0003_ocrfiles_textregion_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrfiles',
            name='textRegion_file',
        ),
        migrations.AddField(
            model_name='ocrconvertedimage',
            name='textRegion_image',
            field=models.FileField(null=True, upload_to='Ocr_files/Ocr_TextRegion_images/%Y/%m/'),
        ),
    ]
